#ifndef market_h
#define market_h


#include <autobahn/autobahn.hpp>
#include <boost/asio.hpp>	
#include <autobahn/autobahn.hpp>
#include <autobahn/wamp_websocketpp_websocket_transport.hpp>
#include <websocketpp/config/asio_no_tls_client.hpp>
#include <websocketpp/client.hpp>
#include <boost/version.hpp>
#include <map>
#include <thread>
#include <mutex>
#include <iostream>
#include <memory>
#include <tuple>
#include <mysql/mysql.h>
#include "offer.cpp"
#include "ask.cpp"
#include "bid.cpp"
#include "parameters.hpp"
using namespace std;


#include <websocketpp/config/asio_client.hpp>

class market
{
	public:
		map<string, float> balances;
		
		list<offer> mytrades;
		list<offer> offers;
 	
		MYSQL_RES *result;
		MYSQL_ROW row;
		MYSQL *sqlconnection, mysql;

		static market & instance();

		int market_connect();
		void setup();

	private:
		market(market const&);
        void operator=(market const&);
		market() {};
};

market &market::instance()
{
	static market inst;
	return inst;	
}

void market::setup()
{
	cout << "setting up" << endl;
	mysql_init(&(this->mysql));
	cout << "setting up" << endl;
	this->sqlconnection = mysql_real_connect(&(this->mysql),"localhost","trader","Immabigfatjuicypassword","trades",0,0,0);
	/*int state = mysql_query(this->sqlconnection, "select * from `trades` where date BETWEEN DATE_SUB(NOW(), INTERVAL 14 DAY)  AND NOW()");

	if (state !=0)
	{
		printf(mysql_error(sqlconnection));
	}
	result = mysql_store_result(sqlconnection);
	while ( ( row=mysql_fetch_row(result)) != NULL )
	{
		cout << row << endl;
     and hello Ryan
	}	*/
}


void ticker_event(const autobahn::wamp_event& event)
{
    //ticker event(event.argument<std::string>(0));   
    cout << "ticker" << endl;
}


void add2(autobahn::wamp_invocation invocation)
{
    auto a = invocation->argument<uint64_t>(0);
    auto b = invocation->argument<uint64_t>(1);

    std::cerr << "Procedure com.examples.calculator.add2 invoked: " << a << ", " << b << std::endl;

    invocation->result(std::make_tuple(a + b));
}


void trade_event(const autobahn::wamp_event& event)
{


	string update = event.argument<std::string>(0);
	if(update.size() > 75)
	{
	    bid bidevent(update);  
	    market::instance().offers.push_front(bidevent);
	    market::instance().offers.pop_back();
	    cout << "bid " << bidevent.rate << endl;
	}
	else
	{
		ask askevent(update);
	    market::instance().offers.push_front(askevent);
	    market::instance().offers.pop_back();
	    cout << "ask " << askevent.rate << endl;
	}
}

void ask_event(const autobahn::wamp_event& event)
{

}

int market::market_connect()
{
	typedef websocketpp::client<websocketpp::config::asio_tls_client> client;
    typedef autobahn::wamp_websocketpp_websocket_transport<websocketpp::config::asio_tls_client> websocket_transport;

    try {
        //std::cerr << "Connecting to realm: " << parameters->realm() << std::endl;

        boost::asio::io_service io;
        //bool debug = parameters->debug();

        client ws_client;
        ws_client.init_asio(&io);
        ws_client.set_tls_init_handler([&](websocketpp::connection_hdl) {
            return websocketpp::lib::make_shared<boost::asio::ssl::context>(boost::asio::ssl::context::tlsv12_client);
        });
        auto transport = std::make_shared < autobahn::wamp_websocketpp_websocket_transport<websocketpp::config::asio_tls_client> >(
                ws_client, "wss://api.poloniex.com:443", true);

        //auto transport = std::make_shared<autobahn::wamp_tcp_transport>(
        //        io, parameters->rawsocket_endpoint(),true);

        // create a WAMP session that talks WAMP-RawSocket over TCP
        auto session = std::make_shared<autobahn::wamp_session>(io, true);

        transport->attach(std::static_pointer_cast<autobahn::wamp_transport_handler>(session));

        // Make sure the continuation futures we use do not run out of scope prematurely.
        // Since we are only using one thread here this can cause the io service to block
        // as a future generated by a continuation will block waiting for its promise to be
        // fulfilled when it goes out of scope. This would prevent the session from receiving
        // responses from the router.
        boost::future<void> connect_future;
        boost::future<void> start_future;
        boost::future<void> join_future;
        boost::future<void> subscribe_future;
        connect_future = transport->connect().then([&](boost::future<void> connected) {
            try {
                connected.get();
            } catch (const std::exception& e) {
                std::cerr << e.what() << std::endl;
                io.stop();
                return;
            }

            std::cerr << "transport connected" << std::endl;

            start_future = session->start().then([&](boost::future<void> started) {
                try {
                    started.get();
                } catch (const std::exception& e) {
                    std::cerr << e.what() << std::endl;
                    io.stop();
                    return;
                }

                std::cerr << "session started" << std::endl;

                join_future = session->join("realm1").then([&](boost::future<uint64_t> joined) {
                    try {
                        std::cerr << "joined realm: " << joined.get() << std::endl;
                    } catch (const std::exception& e) {
                        std::cerr << e.what() << std::endl;
                        io.stop();
                        return;
                    }

                    subscribe_future = session->subscribe("USDT_ETH", &trade_event).then([&] (boost::future<autobahn::wamp_subscription> subscribed)
                    {
                        try {
                            std::cerr << "subscribed to topic: " << subscribed.get().id() << std::endl;
                        }
                        catch (const std::exception& e) {
                            std::cerr << e.what() << std::endl;
                            io.stop();
                            return;
                        }

                    });
                });
            });
        });

        std::cerr << "starting io service" << std::endl;
        io.run();
        while(1){
            cout<<"looping..."<<endl;
            sleep(1);
        }
        std::cerr << "stopped io service" << std::endl;
    }
    catch (std::exception& e) {
        std::cerr << "exception: " << e.what() << std::endl;
      
		return -1;
    }
    return 1;
}


#endif
